## USER
users_registration:
    path: /api/v1/{_locale}/users
    controller: App\UserAccount\RegistrationController
    methods: [POST]
    requirements:
        _locale: en|fr

users_authentication:
    path: /api/v1/{_locale}/users/authenticate
    controller: App\UserAccount\AuthenticationController
    methods: [GET]
    requirements:
        _locale: en|fr

users_info:
    path: /api/v1/{_locale}/users/me
    controller: App\UserAccount\UserInfoController
    methods: [GET]
    requirements:
        _locale: en|fr

chat_list_messages:
    path: /api/v1/{_locale}/chat/messages
    controller: App\Chat\ListChatMessagesController
    methods: [GET]
    requirements:
        _locale: en|fr

chat_send_message:
    path: /api/v1/{_locale}/chat/messages
    controller: App\Chat\SendChatMessageController
    methods: [POST]
    requirements:
        _locale: en|fr