parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    ## SYMFONY ##
    App\Infrastructure\Symfony\RequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    App\Infrastructure\Symfony\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\Infrastructure\Symfony\FixturesCommand:

    ## USER ##
    App\UserAccount\RegistrationController:
        tags: ['controller.service_arguments']

    App\UserAccount\AuthenticationController:
        tags: ['controller.service_arguments']

    App\UserAccount\UserInfoController:
        tags: ['controller.service_arguments']

    App\UserAccount\UserRepository:

    App\UserAccount\UserService:

    App\UserAccount\Token\TokenRepository:

    App\UserAccount\ApiTokenAuthenticator:

    ## CHAT ##
    App\Chat\SendChatMessageController:
        tags: ['controller.service_arguments']

    App\Chat\ListChatMessagesController:
        tags: ['controller.service_arguments']

    App\Chat\MessageRepository:

    ## Game ##
    App\Game\CreateGameController:
        tags: ['controller.service_arguments']

    App\Game\ListGamesController:
        tags: ['controller.service_arguments']

    App\Game\GameInfoController:
        tags: ['controller.service_arguments']

    App\Game\GameRepository: